Rewrite C++ bits to Haskell
cachix/cachix pull request #521
Opened 2023-03-22 16:05 UTC by domenkozar

2023-03-22 17:05 UTC, roberth commented
Oh wow I was going to send some warning fixes because I'd started to include cachix in my local build for tooling reasons. Seems that I may not have to bother with that? Anyway, that doesn't really matter, but...

Heaving read through the diff I'm concerned that doing it this way could cause trouble for you and your users. For instance, if you don't get the sqlite flags from the nix config correctly, you'll trigger #475 again. Also, you'll have to deal with changes to the db schema yourself. Probably other unknowns later.
Meanwhile, we're making progress on language bindings in nix upstream. A contributor is committing to C and Python bindings, so we'll have a good foundation for hsc2hs based bindings: no more template haskell and no more C++ interactions either.
Pick your poison :)

2023-03-22 17:12 UTC, domenkozar commented
Seems like we need to pick the right vfs: https://github.com/NixOS/nix/blob/master/src/libstore/sqlite.cc#L58

I'm not happy about this direction, but we had way too much trouble with C++ and this part of the codebase seems quite stable for now. In the future we can reverse this direction if the bindings become more sane.

2023-03-23 12:42 UTC, sandydoo requested changes
👌

2023-03-23 12:42 UTC, sandydoo commented on cachix/src/Cachix/Client/Store.hs
> +  allPaths <- processGraph (getPath <$> initialPaths) (fmap (concatMap references . rights . List.singleton) . queryPathInfo store)
Do we care about any of the errors returned by `queryPathInfo` here? If not, should we document the reason?

What if we avoid going through a list here? The `.` could also be a `<$>` to be read as the common double fmap pattern.
```suggestion
  let fetchReferences = fmap (either (const []) references) . queryPathInfo store
  allPaths <- processGraph (getPath <$> initialPaths) fetchReferences
```

Or maybe even something really obvious:
```suggestion
  allPaths <- 
    processGraph (getPath <$> initialPaths) $
      queryPathInfo store >=> \case
        Left _ -> pure []
        Right pathInfo -> pure $ references pathInfo
```

2023-03-23 12:42 UTC, sandydoo commented on cachix/src/Cachix/Client/Store.hs
> +data Store = Store Text SQLite.Database
We should document that the `Text` is a store prefix. Maybe a type alias?

2023-03-23 13:56 UTC, sandydoo commented on cachix/src/Cachix/Client/Store.hs
> +  T.dropPrefix storePrefix storePath
The default prefix is `/nix`, so this isn't dropping the `/store/` bit. We might also have to sanitize the prefix to handle any trailing slashes.

2023-03-23 14:41 UTC, merged